#pragma once

#ifndef INCLUDE_MOUNT_ADMISSION_H
#define INCLUDE_MOUNT_ADMISSION_H

enum yai_mount_admission_result {
    YAI_MOUNT_ADMISSION_UNKNOWN = 0,
    YAI_MOUNT_ADMISSION_ALLOW,
    YAI_MOUNT_ADMISSION_DENY,
    YAI_MOUNT_ADMISSION_DEFER
};

#endif
