#pragma once

#ifndef INCLUDE_MOUNT_GRAPH_STATE_H
#define INCLUDE_MOUNT_GRAPH_STATE_H

enum yai_mount_graph_state {
    YAI_MOUNT_GRAPH_STATE_UNKNOWN = 0,
    YAI_MOUNT_GRAPH_STATE_BUILDING,
    YAI_MOUNT_GRAPH_STATE_STABLE,
    YAI_MOUNT_GRAPH_STATE_DEGRADED
};

#endif
