#pragma once

#ifndef INCLUDE_MOUNT_VISIBILITY_H
#define INCLUDE_MOUNT_VISIBILITY_H

enum yai_mount_visibility {
    YAI_MOUNT_VISIBILITY_UNKNOWN = 0,
    YAI_MOUNT_VISIBILITY_PRIVATE,
    YAI_MOUNT_VISIBILITY_SHARED,
    YAI_MOUNT_VISIBILITY_RESTRICTED
};

#endif
