#pragma once

#ifndef INCLUDE_FS_MOUNT_STATE_H
#define INCLUDE_FS_MOUNT_STATE_H

enum yai_fs_mount_state {
    YAI_FS_MOUNT_STATE_UNKNOWN = 0,
    YAI_FS_MOUNT_STATE_ATTACHED,
    YAI_FS_MOUNT_STATE_VISIBLE,
    YAI_FS_MOUNT_STATE_HIDDEN,
    YAI_FS_MOUNT_STATE_FAILED
};

#endif
