#pragma once

#ifndef INCLUDE_FS_WORKSPACE_STATE_H
#define INCLUDE_FS_WORKSPACE_STATE_H

enum yai_fs_workspace_state {
    YAI_FS_WORKSPACE_STATE_UNKNOWN = 0,
    YAI_FS_WORKSPACE_STATE_OPEN,
    YAI_FS_WORKSPACE_STATE_DIRTY,
    YAI_FS_WORKSPACE_STATE_SEALED,
    YAI_FS_WORKSPACE_STATE_CLOSED
};

#endif
