#pragma once

#ifndef INCLUDE_NET_TOPOLOGY_TOPOLOGY_STATE_H
#define INCLUDE_NET_TOPOLOGY_TOPOLOGY_STATE_H

enum yai_net_topology_runtime_state {
    YAI_NET_TOPOLOGY_RUNTIME_UNKNOWN = 0,
    YAI_NET_TOPOLOGY_RUNTIME_BUILDING,
    YAI_NET_TOPOLOGY_RUNTIME_STABLE,
    YAI_NET_TOPOLOGY_RUNTIME_DEGRADED,
    YAI_NET_TOPOLOGY_RUNTIME_PARTITIONED
};

#endif
