#pragma once

#ifndef INCLUDE_NET_OVERLAY_OVERLAY_STATE_H
#define INCLUDE_NET_OVERLAY_OVERLAY_STATE_H

enum yai_net_overlay_state {
    YAI_NET_OVERLAY_STATE_UNKNOWN = 0,
    YAI_NET_OVERLAY_STATE_INIT,
    YAI_NET_OVERLAY_STATE_READY,
    YAI_NET_OVERLAY_STATE_PARTITIONED
};

#endif
