name: Feature request
description: Contract-aware feature request (objective + compatibility + validation plan)
title: "[feat] <short>"
labels: ["type:feature"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      options: ["boot", "kernel", "engine", "root", "runtime", "tools", "docs", "law/specs"]
    validations:
      required: true

  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: What must be true when done?
    validations:
      required: true

  - type: textarea
    id: contract_delta
    attributes:
      label: Contract delta (if any)
      description: Envelope/Authority/Errors/Logging changes.
    validations:
      required: false

  - type: dropdown
    id: compatibility
    attributes:
      label: Compatibility class
      options: ["A", "B", "C", "N/A"]
    validations:
      required: true

  - type: textarea
    id: validation
    attributes:
      label: Validation plan
      description: Positive + negative checks; commands.
      render: bash
    validations:
      required: true
