name: Docs / governance change
description: Templates, policies, docs structure, workflows
title: "[docs] <short>"
labels: ["type:docs"]
body:
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What docs/templates/workflows will change?
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why
      description: What governance gap does this close?
    validations:
      required: true

  - type: textarea
    id: validation
    attributes:
      label: Validation
      description: What checks must pass?
      render: bash
    validations:
      required: true
