#pragma once

#ifndef INCLUDE_FIRMWARE_FORMAT_H
#define INCLUDE_FIRMWARE_FORMAT_H

enum yai_firmware_format {
    YAI_FIRMWARE_FORMAT_UNKNOWN = 0,
    YAI_FIRMWARE_FORMAT_RAW,
    YAI_FIRMWARE_FORMAT_ELF,
    YAI_FIRMWARE_FORMAT_ARCHIVE,
    YAI_FIRMWARE_FORMAT_SIGNED_BLOB
};

#endif
