#pragma once

#ifndef INCLUDE_FIRMWARE_VERIFICATION_H
#define INCLUDE_FIRMWARE_VERIFICATION_H

enum yai_firmware_verification_result {
    YAI_FIRMWARE_VERIFY_UNKNOWN = 0,
    YAI_FIRMWARE_VERIFY_OK,
    YAI_FIRMWARE_VERIFY_MISSING_SIGNATURE,
    YAI_FIRMWARE_VERIFY_BAD_SIGNATURE,
    YAI_FIRMWARE_VERIFY_POLICY_DENIED
};

#endif
