#pragma once

#ifndef INCLUDE_TRANSPORT_STATE_H
#define INCLUDE_TRANSPORT_STATE_H

enum yai_transport_state {
    YAI_TRANSPORT_DOWN = 0,
    YAI_TRANSPORT_INIT,
    YAI_TRANSPORT_READY,
    YAI_TRANSPORT_DEGRADED,
    YAI_TRANSPORT_FAILED
};

#endif
