#pragma once

#ifndef INCLUDE_DEVICE_BUS_TYPE_H
#define INCLUDE_DEVICE_BUS_TYPE_H

enum yai_device_bus_type {
    YAI_DEVICE_BUS_NONE = 0,
    YAI_DEVICE_BUS_PLATFORM,
    YAI_DEVICE_BUS_PCI,
    YAI_DEVICE_BUS_USB,
    YAI_DEVICE_BUS_VIRTIO,
    YAI_DEVICE_BUS_INTERNAL
};

#endif
