#pragma once

#ifndef INCLUDE_DEVICE_STATE_H
#define INCLUDE_DEVICE_STATE_H

enum yai_device_state {
    YAI_DEVICE_DETACHED = 0,
    YAI_DEVICE_DISCOVERED,
    YAI_DEVICE_PROBED,
    YAI_DEVICE_READY,
    YAI_DEVICE_SUSPENDED,
    YAI_DEVICE_FAILED
};

#endif
