#pragma once

#ifndef INCLUDE_NET_CONTROL_CONTROL_STATE_H
#define INCLUDE_NET_CONTROL_CONTROL_STATE_H

enum yai_net_control_state {
    YAI_NET_CONTROL_STATE_UNKNOWN = 0,
    YAI_NET_CONTROL_STATE_IDLE,
    YAI_NET_CONTROL_STATE_ACTIVE,
    YAI_NET_CONTROL_STATE_DEGRADED
};

#endif
