#pragma once

#ifndef INCLUDE_NET_SESSION_SESSION_STATE_H
#define INCLUDE_NET_SESSION_SESSION_STATE_H

enum yai_net_session_state {
    YAI_NET_SESSION_STATE_UNKNOWN = 0,
    YAI_NET_SESSION_STATE_OPEN,
    YAI_NET_SESSION_STATE_ESTABLISHED,
    YAI_NET_SESSION_STATE_DRAINING,
    YAI_NET_SESSION_STATE_CLOSED
};

#endif
