# SPDX-License-Identifier: Apache-2.0
#
# YAI-OS root build spine
# Root owns orchestration, output tree, verbosity and target families.
# Subtrees own local build logic.

ifeq ($(filter output-sync,$(.FEATURES)),)
$(error GNU Make >= 4.0 is required. Your Make version is $(MAKE_VERSION))
endif

$(if $(filter __%,$(MAKECMDGOALS)), \
	$(error targets prefixed with '__' are reserved for internal use))

this-makefile := $(lastword $(MAKEFILE_LIST))
abs_srctree := $(realpath $(dir $(this-makefile)))
abs_output := $(CURDIR)

PHONY := __all
__all:

ifneq ($(sub_make_done),1)

MAKEFLAGS += -rR

unexport LC_ALL
LC_COLLATE := C
LC_NUMERIC := C
export LC_COLLATE LC_NUMERIC

ifeq ("$(origin V)","command line")
KBUILD_VERBOSE := $(V)
endif

quiet := quiet_
Q := @

ifneq ($(findstring 1,$(KBUILD_VERBOSE)),)
quiet :=
Q :=
endif

ifneq ($(findstring s,$(firstword -$(MAKEFLAGS))),)
quiet := silent_
override KBUILD_VERBOSE :=
endif

export quiet Q KBUILD_VERBOSE

ROOT_DIR := $(abs_srctree)
ARCH ?= x86_64
HOST_OS ?= $(shell uname -s | tr '[:upper:]' '[:lower:]')
O ?=
export ROOT_DIR ARCH HOST_OS

ifeq ("$(origin O)","command line")
KBUILD_OUTPUT := $(O)
endif

ifdef KBUILD_OUTPUT
$(shell mkdir -p "$(KBUILD_OUTPUT)")
abs_output := $(realpath $(KBUILD_OUTPUT))
$(if $(abs_output),,$(error failed to create output directory "$(KBUILD_OUTPUT)"))
endif

ifneq ($(words $(subst :, ,$(abs_srctree))),1)
$(error source directory cannot contain spaces or colons)
endif

export sub_make_done := 1

endif

ifeq ($(abs_output),$(CURDIR))
no-print-directory := --no-print-directory
else
need-sub-make := 1
endif

ifeq ($(filter --no-print-directory,$(MAKEFLAGS)),)
need-sub-make := 1
endif

ifeq ($(need-sub-make),1)

PHONY += $(MAKECMDGOALS) __sub-make

$(filter-out $(this-makefile),$(MAKECMDGOALS)) __all: __sub-make
	@:

__sub-make:
	$(Q)$(MAKE) $(no-print-directory) -C $(abs_output) -f $(abs_srctree)/Makefile $(MAKECMDGOALS)

else

srctree := $(abs_srctree)
objtree := $(abs_output)

export srctree objtree

ROOT_BUILD_DIR := $(objtree)
CONFIG_DIR := $(objtree)/config
GEN_INCLUDE_DIR := $(objtree)/include/generated
BIN_DIR := $(objtree)/bin
LIB_DIR := $(objtree)/lib
OBJ_DIR := $(objtree)/obj
TMP_DIR := $(objtree)/tmp

export ROOT_BUILD_DIR CONFIG_DIR GEN_INCLUDE_DIR BIN_DIR LIB_DIR OBJ_DIR TMP_DIR

-include $(CONFIG_DIR)/auto.conf

SUPPORTED_ARCHES := x86_64 aarch64 riscv64
CORE_SUBDIRS := arch include ipc kernel lib mm net security drivers fs
EXT_SUBDIRS := block crypto io_uring virt
YAI_SUBDIRS := container graph policy governance usr tools scripts Documentation
ALL_SUBDIRS := $(CORE_SUBDIRS) $(EXT_SUBDIRS) $(YAI_SUBDIRS)

PHONY += all help prepare archcheck headers core yai clean mrproper distclean \
	  docs dist check outputmakefile \
	  $(ALL_SUBDIRS)

__all: all

all: prepare core yai

define descend-dir
	@echo "[YAI-OS] $(1)"
	$(Q)$(MAKE) -C $(srctree)/$(1) O=$(objtree) ARCH=$(ARCH) HOST_OS=$(HOST_OS)
endef

archcheck:
	@case "$(ARCH)" in \
		x86_64|aarch64|riscv64) ;; \
		*) echo "Unsupported ARCH=$(ARCH)"; exit 1 ;; \
	esac

prepare: archcheck outputmakefile
	$(Q)mkdir -p \
		$(CONFIG_DIR) \
		$(GEN_INCLUDE_DIR) \
		$(BIN_DIR) \
		$(LIB_DIR) \
		$(OBJ_DIR) \
		$(TMP_DIR)
	@echo "[YAI-OS] prepare ARCH=$(ARCH) HOST_OS=$(HOST_OS) O=$(objtree)"

outputmakefile:
ifneq ($(objtree),$(srctree))
	$(Q){ \
		echo "# Automatically generated by $(srctree)/Makefile: do not edit"; \
		echo "export O := $(objtree)"; \
		echo "include $(srctree)/Makefile"; \
	} > $(objtree)/Makefile
	$(Q)test -e $(objtree)/.gitignore || { echo "# build directory"; echo "*"; } > $(objtree)/.gitignore
endif

headers: prepare include arch
	@echo "[YAI-OS] headers ready"

core: prepare $(CORE_SUBDIRS)

yai: prepare $(YAI_SUBDIRS)

arch:
	$(call descend-dir,arch)

include:
	$(call descend-dir,include)

ipc:
	$(call descend-dir,ipc)

kernel:
	$(call descend-dir,kernel)

lib:
	$(call descend-dir,lib)

mm:
	$(call descend-dir,mm)

net:
	$(call descend-dir,net)

security:
	$(call descend-dir,security)

drivers:
	$(call descend-dir,drivers)

fs:
	$(call descend-dir,fs)

block:
	$(call descend-dir,block)

crypto:
	$(call descend-dir,crypto)

io_uring:
	$(call descend-dir,io_uring)

virt:
	$(call descend-dir,virt)

container:
	$(call descend-dir,container)

graph:
	$(call descend-dir,graph)

policy:
	$(call descend-dir,policy)

governance:
	$(call descend-dir,governance)

usr:
	$(call descend-dir,usr)

tools:
	$(call descend-dir,tools)

scripts:
	$(call descend-dir,scripts)

Documentation:
	$(call descend-dir,Documentation)

docs: Documentation

dist:
	@echo "[YAI-OS] dist staging not wired yet"

check:
	@echo "[YAI-OS] check pipeline not wired yet"

clean:
	@echo "[YAI-OS] clean $(objtree)"
	$(Q)rm -rf \
		$(BIN_DIR) \
		$(LIB_DIR) \
		$(OBJ_DIR) \
		$(TMP_DIR)

mrproper: clean
	@echo "[YAI-OS] mrproper $(objtree)"
	$(Q)rm -rf \
		$(CONFIG_DIR) \
		$(objtree)/include/generated \
		$(objtree)/Makefile \
		$(objtree)/.gitignore
	$(Q)find $(srctree) \( -name '*~' -o -name '*.bak' -o -name '*.orig' -o -name '*.rej' \) -type f -print | xargs rm -f 2>/dev/null || true

distclean: mrproper
	@echo "[YAI-OS] distclean complete"

help:
	@echo "YAI-OS root targets:"
	@echo "  make [ARCH=x86_64|aarch64|riscv64] [O=out] all"
	@echo "  make prepare"
	@echo "  make headers"
	@echo "  make core"
	@echo "  make yai"
	@echo "  make docs"
	@echo "  make clean"
	@echo "  make mrproper"
	@echo "  make distclean"
	@echo ""
	@echo "Directory targets:"
	@echo "  $(ALL_SUBDIRS)"
	@echo ""
	@echo "Build flags:"
	@echo "  V=1     verbose build"
	@echo "  O=dir   output directory"

endif

PHONY += FORCE
FORCE:

.PHONY: $(PHONY)