use crate::interface::tui::app::{DbScope, ViewKind};

#[derive(Debug, Clone)]
pub enum Action {
    Tick,
    Refresh,
    ToggleHelp,
    FocusNext,
    MoveUp,
    MoveDown,
    Select,
    SwitchView(ViewKind),
    SelectWs(String),
    RunCommand(String),
    GraphSelectNode(String),
    GraphNeighbors { id: String, depth: usize },
    GraphToggleDepth,
    GraphActivateSelected,
    LogsSelectSource(String),
    LogsCycleSource,
    LogsToggleFollow,
    LogsSearch(String),
    DbSelect(DbScope),
    DbSelectTable(String),
    ProvidersSelect(String),
    ProvidersTrust { id: String, state: String },
    ChatSetInput(String),
    ChatSend(String),
    ChatInputNewline,
    ChatClearInput,
    ChatToggleStreaming,
    ChatCycleCommitTarget,
    ChatRetry,
    ChatApplyDraft,
    ChatDiscardDraft,
    TogglePalette,
    PaletteInput(String),
}
