#pragma once

#ifndef INCLUDE_SYS_BOOT_PHASE_H
#define INCLUDE_SYS_BOOT_PHASE_H

enum yai_boot_phase {
    YAI_BOOT_PHASE_EARLY = 0,
    YAI_BOOT_PHASE_DISCOVERY,
    YAI_BOOT_PHASE_MOUNT,
    YAI_BOOT_PHASE_POLICY,
    YAI_BOOT_PHASE_RUNTIME
};

#endif
